const SLACK_EMOJI: Record<string, string> = {
  // Thumbs / hands
  thumbsup: '👍', '+1': '👍', thumbsdown: '👎', '-1': '👎',
  clap: '👏', clapping: '👏', raised_hands: '🙌', pray: '🙏',
  ok_hand: '👌', point_up: '☝️', point_up_2: '👆', point_right: '👉',
  point_left: '👈', point_down: '👇', wave: '👋', raised_hand: '✋',
  muscle: '💪', pinched_fingers: '🤌', handshake: '🤝', fist: '✊',
  v: '✌️', crossed_fingers: '🤞', love_you_gesture: '🤟', metal: '🤘',
  call_me_hand: '🤙', open_hands: '👐', palms_up_together: '🤲',
  writing_hand: '✍️', nail_care: '💅', selfie: '🤳',

  // Faces — positive
  smile: '😄', grinning: '😀', smiley: '😃', grin: '😁',
  joy: '😂', rofl: '🤣', sweat_smile: '😅', laughing: '😆',
  slightly_smiling_face: '🙂', upside_down_face: '🙃', wink: '😉',
  blush: '😊', innocent: '😇', star_struck: '🤩', heart_eyes: '😍',
  kissing_heart: '😘', kissing: '😗', kissing_closed_eyes: '😚',
  kissing_smiling_eyes: '😙', yum: '😋', stuck_out_tongue: '😛',
  stuck_out_tongue_winking_eye: '😜', zany_face: '🤪',
  stuck_out_tongue_closed_eyes: '😝', money_mouth_face: '🤑',
  hugs: '🤗', smiling_face_with_3_hearts: '🥰',

  // Faces — neutral / thinking
  thinking_face: '🤔', raised_eyebrow: '🤨', neutral_face: '😐',
  expressionless: '😑', no_mouth: '😶', smirk: '😏', unamused: '😒',
  zipper_mouth_face: '🤐', shushing_face: '🤫', face_with_monocle: '🧐',
  face_with_raised_eyebrow: '🤨', saluting_face: '🫡',

  // Faces — negative
  confused: '😕', worried: '😟', slightly_frowning_face: '🙁',
  frowning_face: '☹️', open_mouth: '😮', hushed: '😯',
  astonished: '😲', flushed: '😳', pleading_face: '🥺',
  anguished: '😧', fearful: '😨', cold_sweat: '😰', cry: '😢',
  sob: '😭', scream: '😱', confounded: '😖', persevere: '😣',
  disappointed_relieved: '😥', weary: '😩', tired_face: '😫',
  yawning_face: '🥱', face_with_steam_from_nose: '😤',
  triumph: '😤', rage: '😡', angry: '😠', skull: '💀',
  face_vomiting: '🤮', sneezing_face: '🤧', hot_face: '🥵',
  cold_face: '🥶', woozy_face: '🥴', dizzy_face: '😵',
  exploding_head: '🤯', face_with_symbols_on_mouth: '🤬',

  // Faces — misc
  sunglasses: '😎', nerd_face: '🤓', monocle_face: '🧐',
  partying_face: '🥳', disguised_face: '🥸', lying_face: '🤥',
  sleeping: '😴', sleepy: '😪', mask: '😷', face_with_thermometer: '🤒',
  face_with_head_bandage: '🤕', ghost: '👻', robot: '🤖',
  clown_face: '🤡', japanese_ogre: '👹', japanese_goblin: '👺',
  skull_and_crossbones: '☠️', alien: '👽', space_invader: '👾',

  // Hearts / love
  heart: '❤️', orange_heart: '🧡', yellow_heart: '💛',
  green_heart: '💚', blue_heart: '💙', purple_heart: '💜',
  brown_heart: '🤎', black_heart: '🖤', white_heart: '🤍',
  broken_heart: '💔', heart_exclamation: '❣️', two_hearts: '💕',
  revolving_hearts: '💞', heartbeat: '💓', heartpulse: '💗',
  sparkling_heart: '💖', cupid: '💘', gift_heart: '💝', heart_decoration: '💟',

  // Symbols / marks
  white_check_mark: '✅', heavy_check_mark: '✔️', x: '❌',
  heavy_multiplication_x: '✖️', negative_squared_cross_mark: '❎',
  o: '⭕', question: '❓', grey_question: '❔', grey_exclamation: '❕',
  exclamation: '❗', heavy_exclamation_mark: '❗', warning: '⚠️',
  no_entry: '⛔', no_entry_sign: '🚫', prohibited: '🚫',
  '100': '💯', keycap_ten: '🔟', recycle: '♻️', sos: '🆘',
  up: '🆙', cool: '🆒', free: '🆓', new: '🆕', ng: '🆖',
  ok: '🆗', sos2: '🆘', id: '🆔', end: '🔚', back: '🔙',
  on: '🔛', top: '🔝', soon: '🔜',

  // Objects / things
  fire: '🔥', tada: '🎉', sparkles: '✨', star: '⭐', star2: '🌟',
  dizzy: '💫', boom: '💥', anger: '💢', speech_balloon: '💬',
  thought_balloon: '💭', zzz: '💤', wave2: '🌊', dash: '💨',
  sweat_drops: '💦', umbrella: '☂️', bulb: '💡', flashlight: '🔦',
  memo: '📝', pencil: '✏️', paperclip: '📎', scissors: '✂️',
  lock: '🔒', unlock: '🔓', key: '🔑', bell: '🔔', no_bell: '🔕',
  loudspeaker: '📢', mega: '📣', email: '📧', envelope: '✉️',
  mailbox: '📫', phone: '📱', computer: '💻', desktop_computer: '🖥️',
  printer: '🖨️', keyboard: '⌨️', computer_mouse: '🖱️',
  trackball: '🖲️', minidisc: '💽', floppy_disk: '💾',
  cd: '💿', dvd: '📀', movie_camera: '🎥', film_projector: '📽️',
  clapper: '🎬', tv: '📺', radio: '📻', saxophone: '🎷',
  guitar: '🎸', musical_note: '🎵', notes: '🎶', microphone: '🎤',
  headphones: '🎧', trophy: '🏆', medal_sports: '🏅', '1st_place_medal': '🥇',
  '2nd_place_medal': '🥈', '3rd_place_medal': '🥉', dart: '🎯',
  game_die: '🎲', chess_pawn: '♟️', jigsaw: '🧩', balloon: '🎈',
  gift: '🎁', ribbon: '🎀', party_popper: '🎉', confetti_ball: '🎊',
  fireworks: '🎆', sparkler: '🎇', flag: '🚩', flags: '🎏',

  // Nature / animals
  dog: '🐶', cat: '🐱', mouse: '🐭', hamster: '🐹', rabbit: '🐰',
  fox_face: '🦊', bear: '🐻', panda_face: '🐼', koala: '🐨',
  tiger: '🐯', lion: '🦁', cow: '🐮', pig: '🐷', frog: '🐸',
  monkey_face: '🐵', chicken: '🐔', penguin: '🐧', bird: '🐦',
  hatching_chick: '🐣', hatched_chick: '🐥', duck: '🦆', eagle: '🦅',
  owl: '🦉', bat: '🦇', wolf: '🐺', boar: '🐗', horse: '🐴',
  unicorn: '🦄', bee: '🐝', bug: '🐛', butterfly: '🦋', snail: '🐌',
  shell: '🐚', crab: '🦀', lobster: '🦞', shrimp: '🦐', octopus: '🐙',
  tropical_fish: '🐠', blowfish: '🐡', shark: '🦈', whale: '🐳',
  dolphin: '🐬', seedling: '🌱', evergreen_tree: '🌲', deciduous_tree: '🌳',
  palm_tree: '🌴', cactus: '🌵', ear_of_rice: '🌾', herb: '🌿',
  shamrock: '☘️', four_leaf_clover: '🍀', maple_leaf: '🍁',
  fallen_leaf: '🍂', leaves: '🍃', mushroom: '🍄', rose: '🌹',
  sunflower: '🌻', blossom: '🌸', cherry_blossom: '🌸', hibiscus: '🌺',
  sun: '☀️', full_moon: '🌕', crescent_moon: '🌙', cloud: '☁️',
  rainbow: '🌈', snowflake: '❄️', fire2: '🔥', droplet: '💧',
  ocean: '🌊',

  // Food
  pizza: '🍕', hamburger: '🍔', hotdog: '🌭', taco: '🌮',
  burrito: '🌯', salad: '🥗', spaghetti: '🍝', ramen: '🍜',
  sushi: '🍣', bento: '🍱', rice: '🍚', bread: '🍞',
  croissant: '🥐', avocado: '🥑', egg: '🥚', cheese: '🧀',
  bacon: '🥓', steak: '🥩', poultry_leg: '🍗', cut_of_meat: '🥩',
  apple: '🍎', green_apple: '🍏', pear: '🍐', tangerine: '🍊',
  lemon: '🍋', banana: '🍌', watermelon: '🍉', grapes: '🍇',
  strawberry: '🍓', melon: '🍈', cherries: '🍒', peach: '🍑',
  mango: '🥭', pineapple: '🍍', blueberries: '🫐', kiwi_fruit: '🥝',
  cake: '🎂', birthday: '🎂', cupcake: '🧁', pie: '🥧',
  candy: '🍬', chocolate_bar: '🍫', icecream: '🍦', ice_cream: '🍨',
  doughnut: '🍩', cookie: '🍪', coffee: '☕', tea: '🍵',
  beer: '🍺', beers: '🍻', wine_glass: '🍷', champagne: '🍾',
  cocktail: '🍹', tropical_drink: '🍹', milk_glass: '🥛',

  // People / gestures
  man: '👨', woman: '👩', boy: '👦', girl: '👧', baby: '👶',
  older_man: '👴', older_woman: '👵', family: '👨‍👩‍👦',
  couple: '👫', two_men_holding_hands: '👬', two_women_holding_hands: '👭',
  dancer: '💃', man_dancing: '🕺', runner: '🏃', walking: '🚶',
  person_facepalming: '🤦', man_facepalming: '🤦‍♂️',
  woman_facepalming: '🤦‍♀️', person_shrugging: '🤷',
  man_shrugging: '🤷‍♂️', woman_shrugging: '🤷‍♀️',

  // Activities / sports
  soccer: '⚽', basketball: '🏀', football: '🏈', baseball: '⚾',
  tennis: '🎾', volleyball: '🏐', rugby_football: '🏉', flying_disc: '🥏',
  '8ball': '🎱', ping_pong: '🏓', badminton: '🏸', goal_net: '🥅',
  golf: '⛳', fishing_pole_and_fish: '🎣', boxing_glove: '🥊',
  martial_arts_uniform: '🥋', ice_skate: '⛸️', ski: '🎿',
  snowboarder: '🏂', surfer: '🏄', swimmer: '🏊', cyclist: '🚴',
  trophy2: '🏆', checkered_flag: '🏁', sports_medal: '🏅',

  // Travel / places
  car: '🚗', taxi: '🚕', bus: '🚌', trolleybus: '🚎', racing_car: '🏎️',
  police_car: '🚓', ambulance: '🚑', fire_engine: '🚒', minibus: '🚐',
  truck: '🚚', train: '🚆', airplane: '✈️', rocket: '🚀',
  flying_saucer: '🛸', ship: '🚢', sailboat: '⛵', speedboat: '🚤',
  house: '🏠', office: '🏢', hospital: '🏥', bank: '🏦',
  hotel: '🏨', school: '🏫', japanese_castle: '🏯', statue_of_liberty: '🗽',
  earth_americas: '🌎', earth_africa: '🌍', earth_asia: '🌏',
  world_map: '🗺️', japan: '🗾', compass: '🧭', mountain: '⛰️',
  national_park: '🏞️', stadium: '🏟️', moyai: '🗿',

  // Tech / misc
  brain: '🧠', eyes: '👀', ear: '👂', nose: '👃', tooth: '🦷',
  bone: '🦴', leg: '🦵', foot: '🦶', footprints: '👣',
  white_flower: '💮', heavy_plus_sign: '➕', heavy_minus_sign: '➖',
  heavy_division_sign: '➗', curly_loop: '➰', loop: '➿',
  arrow_right: '➡️', arrow_left: '⬅️', arrow_up: '⬆️', arrow_down: '⬇️',
  repeat: '🔁', repeat_one: '🔂', arrows_counterclockwise: '🔄',
  twisted_rightwards_arrows: '🔀', fast_forward: '⏩', rewind: '⏪',
  clock1: '🕐', alarm_clock: '⏰', hourglass: '⌛', hourglass_flowing_sand: '⏳',
  calendar: '📅', date: '📅', card_index: '📇', chart_with_upwards_trend: '📈',
  chart_with_downwards_trend: '📉', bar_chart: '📊', clipboard: '📋',
  pushpin: '📌', round_pushpin: '📍', triangular_ruler: '📐',
  straight_ruler: '📏', bookmark_tabs: '📑', ledger: '📒',
  books: '📚', book: '📖', scroll: '📜', newspaper: '📰',
  moneybag: '💰', yen: '💴', dollar: '💵', euro: '💶',
  pound: '💷', money_with_wings: '💸', credit_card: '💳',
  gem: '💎', ring: '💍', shopping: '🛍️', shopping_cart: '🛒',
  hammer: '🔨', wrench: '🔧', nut_and_bolt: '🔩', gear: '⚙️',
  chains: '⛓️', gun: '🔫', bomb: '💣', knife: '🔪', dagger: '🗡️',
  sword: '⚔️', shield: '🛡️', smoking: '🚬', coffin: '⚰️',
  amphora: '🏺', crystal_ball: '🔮', nazar_amulet: '🧿', compass2: '🧭',
  test_tube: '🧪', petri_dish: '🧫', dna: '🧬', safety_pin: '🧷',
  broom: '🧹', basket: '🧺', roll_of_paper: '🧻', soap: '🧼',
  sponge: '🧽', lotion_bottle: '🧴', thread: '🧵', yarn: '🧶',
}

export function slackEmojiChar(name: string): string {
  return SLACK_EMOJI[name] || `:${name}:`
}
